'use client'

import { Button } from './ui/Button'
import { BookOpen, Target, Zap, Clock, Award, ArrowRight, Calculator, FileText, PenTool } from 'lucide-react'
import Link from 'next/link'
import quantitativeScreenshot from '../../screenshots/quantiative.png'
import readingScreenshot from '../../screenshots/reading.png'
import Image from 'next/image'

interface HomePageProps {
  showChinese?: boolean
}

export function HomePage({ showChinese = false }: HomePageProps) {
  // console.log('🔄 HomePage: Component rendering')
  
  // UI translations
  const translations = {
    'SmartSSAT': 'SmartSSAT',
    'Master the': '通过',
    'SSAT': 'AI智能练习',
    'with': ' ',
    'AI-Powered Practice': '高效掌握SSAT考试',
    'Generate personalized SSAT practice questions with AI. Practice individual sections or take complete tests.': 
    '使用AI生成个性化SSAT练习题。支持单项练习或完整测试。',
    'Start Single Section Practice': '开始单项练习',
    'Start Full Test Practice': '开始完整测试',
    'Why Choose SmartSSAT?': '为什么选择SmartSSAT？',
    'Our AI-driven platform delivers personalized SSAT practice with instant feedback and comprehensive explanations.':
    '我们的AI智能平台提供个性化SSAT练习，即时反馈和全面解析。',
    'AI-Generated Questions': 'AI生成题目',
    'Get practice questions that match the SSAT format and difficulty, generated by advanced AI models.':
    '获取由先进AI模型生成的、符合SSAT格式和难度的练习题。',
    'Personalized Practice': '个性化练习',
    'Choose your preferred sections, difficulty levels, and topics to focus on your specific needs.':
    '选择您偏好的科目、难度级别和主题，专注于您的特定需求。',
    'Answer Key & Solutions': '答案与解析',
    'Get correct answers and explanations to help you understand the concepts and improve your skills.':
    '获取正确答案和解析，帮助您理解概念并提升技能。',
    'Choose Your Practice Mode': '选择您的练习模式',
    'Flexible options to match your study schedule and goals.': '灵活配置，满足不同学习需求与时间安排。',
    'Single Section Practice': '单项练习',
    'Targeted Learning': '专项学习',
    'Choose any section (Math, Verbal, Reading, Writing)': '可选择任意科目（数学、词汇、阅读、写作）',
    'Select difficulty level and number of questions': '选择题目难度和数量',
    'Focus on specific topics within sections': '可聚焦具体知识点进行强化',
    'Perfect for quick practice sessions': '适合日常短时间练习',
    'Complete Practice Test': '完整模拟测试',
    'Complete Assessment': '全面评估',
    'Official SSAT format with all sections': '按照SSAT官方格式，涵盖所有考试部分',
    'Customizable section configuration': '支持灵活定制考试科目组合',
    'Comprehensive answer key with explanations': '提供全套答案与详尽解析',
    'PDF export for offline practice': '支持PDF导出，便于线下练习',
    'Standard SSAT format with multiple sections': '按照SSAT标准格式，涵盖所有考试部分',
    'SSAT Test Sections': 'SSAT考试科目一览',
    'Comprehensive coverage of all SSAT sections with authentic question types.':
    '全面覆盖SSAT各科目，题型真实，贴合考试要求。',
    'Quantitative': '数学',
    'Mathematical reasoning and problem-solving skills': '数学推理和问题解决能力',
    'Verbal': '语言',
    'Vocabulary and verbal reasoning skills': '词汇和语言推理能力',
    'Reading': '阅读',
    'Reading comprehension and analysis': '阅读理解与分析',
    'Writing': '写作',
    'Creative writing and essay skills': '创意写作和文章技能',
    // Topics
    'Fractions': '分数',
    'Algebra': '代数',
    'Geometry': '几何',
    'Word Problems': '应用题',
    'Synonyms': '同义词',
    'Analogies': '类比',
    'Vocabulary': '词汇',
    'Word Relationships': '词汇关系',
    'Literature': '文学',
    'Science': '科学',
    'History': '历史',
    'Critical Reading': '批判性阅读',
    'Grammar': '语法',
    'Punctuation': '标点',
    'Sentence Structure': '句子结构',
    'Style': '写作风格',
    'See SmartSSAT in Action': '体验SmartSSAT实际效果',
    'Experience our AI-powered SSAT practice platform with real questions and detailed explanations.':
    '体验我们的AI智能SSAT练习平台，真实题目与详细解析。',
    'Quantitative Practice': '数学练习',
    'Mathematical reasoning questions with step-by-step explanations': '数学推理题目，配有逐步解析',
    'Reading Comprehension': '阅读理解',
    'Reading passages with comprehension questions and detailed analysis': '阅读文章配有理解题目和详细分析'
  }

  const t = (key: string) => showChinese ? (translations[key as keyof typeof translations] || key) : key

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      {/* Hero Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              {t('Master the')} <span className="text-blue-600">{t('SSAT')}</span> {t('with')}
              <br className="mb-4" />
              <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                {t('AI-Powered Practice')}
              </span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
              {t('Generate personalized SSAT practice questions with AI. Practice individual sections or take complete tests.')}
            </p>
            <div className="flex flex-col md:flex-row gap-6 justify-center max-w-4xl mx-auto">
              <Link href="/custom-section" className="flex-1">
                <Button size="lg" className="w-full inline-flex items-center justify-center px-6 py-4 text-lg shadow-lg hover:shadow-xl transition-all duration-200 rounded-xl">
                  <Target className="mr-2 h-5 w-5" />
                  {t('Start Single Section Practice')}
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
              <Link href="/full-test" className="flex-1">
                <Button 
                  variant="outline" 
                  size="lg" 
                  className="w-full inline-flex items-center justify-center px-6 py-4 text-lg bg-white border-2 border-gray-200 text-gray-700 hover:bg-gray-50 hover:border-gray-300 shadow-lg hover:shadow-xl transition-all duration-200 rounded-xl"
                >
                  <BookOpen className="mr-2 h-5 w-5" />
                  {t('Start Full Test Practice')}
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>



      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              {t('Why Choose SmartSSAT?')}
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              {t('Our AI-driven platform delivers personalized SSAT practice with instant feedback and comprehensive explanations.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center p-8 rounded-2xl bg-white border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-200">
              <div className="bg-blue-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                <Zap className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('AI-Generated Questions')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Get practice questions that match the SSAT format and difficulty, generated by advanced AI models.')}
              </p>
            </div>
            
            <div className="text-center p-8 rounded-2xl bg-white border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-200">
              <div className="bg-green-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                <Target className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('Personalized Practice')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Choose your preferred sections, difficulty levels, and topics to focus on your specific needs.')}
              </p>
            </div>
            
            <div className="text-center p-8 rounded-2xl bg-white border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-200">
              <div className="bg-purple-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                <Award className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('Answer Key & Solutions')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Get correct answers and explanations to help you understand the concepts and improve your skills.')}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Test Modes Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('Choose Your Practice Mode')}</h2>
            <p className="text-lg text-gray-600">
              {t('Flexible options to match your study schedule and goals.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            <Link href="/custom-section" className="group">
              <div className="bg-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-200 border border-gray-100 group-hover:border-blue-200 group-hover:-translate-y-1">
                <div className="flex items-center mb-6">
                  <div className="bg-blue-600 p-3 rounded-xl mr-4 shadow-md">
                    <Target className="h-8 w-8 text-white" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-semibold text-gray-900">{t('Single Section Practice')}</h3>
                    <p className="text-blue-600 font-medium">{t('Targeted Learning')}</p>
                  </div>
                </div>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-blue-600 rounded-full mr-3"></div>
                    <span>{t('Choose any section (Math, Verbal, Reading, Writing)')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-blue-600 rounded-full mr-3"></div>
                    <span>{t('Select difficulty level and number of questions')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-blue-600 rounded-full mr-3"></div>
                    <span>{t('Focus on specific topics within sections')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-blue-600 rounded-full mr-3"></div>
                    <span>{t('Perfect for quick practice sessions')}</span>
                  </li>
                </ul>
              </div>
            </Link>
            
            <Link href="/full-test" className="group">
              <div className="bg-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-200 border border-gray-100 group-hover:border-purple-200 group-hover:-translate-y-1">
                <div className="flex items-center mb-6">
                  <div className="bg-purple-600 p-3 rounded-xl mr-4 shadow-md">
                    <BookOpen className="h-8 w-8 text-white" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-semibold text-gray-900">{t('Complete Practice Test')}</h3>
                    <p className="text-purple-600 font-medium">{t('Complete Assessment')}</p>
                  </div>
                </div>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-purple-600 rounded-full mr-3"></div>
                    <span>{t('Official SSAT format with all sections')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-purple-600 rounded-full mr-3"></div>
                    <span>{t('Customizable section configuration')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-purple-600 rounded-full mr-3"></div>
                    <span>{t('Comprehensive answer key with explanations')}</span>
                  </li>
                  <li className="flex items-center">
                    <div className="w-2 h-2 bg-purple-600 rounded-full mr-3"></div>
                    <span>{t('PDF export for offline practice')}</span>
                  </li>
                </ul>
              </div>
            </Link>
          </div>
        </div>
      </section>

      {/* Product Showcase Section */}
      <section className="py-20 bg-gradient-to-br from-gray-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('See SmartSSAT in Action')}</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              {t('Experience our AI-powered SSAT practice platform with real questions and detailed explanations.')}
            </p>
          </div>
          
          <div className="space-y-16 max-w-6xl mx-auto">
            <div className="space-y-6">
              <h3 className="text-2xl font-semibold text-gray-900 text-center">{t('Quantitative Practice')}</h3>
              <div className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-100 hover:shadow-3xl transition-shadow duration-300">
                <Image 
                  src={quantitativeScreenshot} 
                  alt="SmartSSAT Quantitative Practice Interface"
                  width={1000}
                  height={700}
                  className="w-full h-auto"
                />
              </div>
              <p className="text-base text-gray-600 text-center leading-relaxed max-w-3xl mx-auto">
                {t('Mathematical reasoning questions with step-by-step explanations')}
              </p>
            </div>
            
            <div className="space-y-6">
              <h3 className="text-2xl font-semibold text-gray-900 text-center">{t('Reading Comprehension')}</h3>
              <div className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-100 hover:shadow-3xl transition-shadow duration-300">
                <Image 
                  src={readingScreenshot} 
                  alt="SmartSSAT Reading Practice Interface"
                  width={1000}
                  height={700}
                  className="w-full h-auto"
                />
              </div>
              <p className="text-base text-gray-600 text-center leading-relaxed max-w-3xl mx-auto">
                {t('Reading passages with comprehension questions and detailed analysis')}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* SSAT Sections Info */}
      <section className="py-20 bg-white/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('SSAT Test Sections')}</h2>
            <p className="text-lg text-gray-600">
              {t('Comprehensive coverage of all SSAT sections with authentic question types.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                title: t('Quantitative'),
                description: t('Mathematical reasoning and problem-solving skills'),
                topics: [t('Fractions'), t('Algebra'), t('Geometry'), t('Word Problems')],
                color: 'blue',
                icon: Calculator
              },
              {
                title: t('Verbal'),
                description: t('Vocabulary and verbal reasoning skills'),
                topics: [t('Synonyms'), t('Analogies'), t('Vocabulary'), t('Word Relationships')],
                color: 'green',
                icon: BookOpen
              },
              {
                title: t('Reading'),
                description: t('Reading comprehension and analysis'),
                topics: [t('Literature'), t('Science'), t('History'), t('Critical Reading')],
                color: 'purple',
                icon: FileText
              },
              {
                title: t('Writing'),
                description: t('Creative writing and essay skills'),
                topics: [t('Grammar'), t('Punctuation'), t('Sentence Structure'), t('Style')],
                color: 'orange',
                icon: PenTool
              }
            ].map((section, index) => {
              const getColorClasses = (color: string) => {
                switch (color) {
                  case 'blue':
                    return {
                      bg: 'bg-blue-100',
                      text: 'text-blue-600',
                      textDark: 'text-blue-700'
                    }
                  case 'green':
                    return {
                      bg: 'bg-green-100',
                      text: 'text-green-600',
                      textDark: 'text-green-700'
                    }
                  case 'purple':
                    return {
                      bg: 'bg-purple-100',
                      text: 'text-purple-600',
                      textDark: 'text-purple-700'
                    }
                  case 'orange':
                    return {
                      bg: 'bg-orange-100',
                      text: 'text-orange-600',
                      textDark: 'text-orange-700'
                    }
                  default:
                    return {
                      bg: 'bg-gray-100',
                      text: 'text-gray-600',
                      textDark: 'text-gray-700'
                    }
                }
              }
              
              const colors = getColorClasses(section.color)
              
              return (
                <div key={index} className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
                  <div className="flex items-center mb-4">
                    <div className={`${colors.bg} p-3 rounded-lg mr-4`}>
                      <section.icon className={`h-6 w-6 ${colors.text}`} />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900">{section.title}</h3>
                      <p className="text-sm text-gray-600">{section.description}</p>
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {section.topics.map((topic, topicIndex) => (
                      <span
                        key={topicIndex}
                        className={`px-3 py-1 text-xs font-medium ${colors.bg} ${colors.textDark} rounded-full`}
                      >
                        {topic}
                      </span>
                    ))}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>
    </div>
  )
}