'use client'

import { Button } from './ui/Button'
import { BookOpen, FileText, Target, Zap, Clock, Award, ArrowRight } from 'lucide-react'
import Link from 'next/link'

interface HomePageProps {
  showChinese?: boolean
}

export function HomePage({ showChinese = false }: HomePageProps) {
  // console.log('🔄 HomePage: Component rendering')
  
  // UI translations
  const translations = {
    'Master the': '掌握',
    'SSAT': 'SSAT',
    'with': '通过',
    'AI-Generated Practice': 'AI生成的练习',
    'Get unlimited, personalized SSAT practice questions generated by advanced AI. Practice individual sections or take full-length tests with instant feedback and detailed explanations.': '获得由先进AI生成的无限制个性化SSAT练习题。练习单独部分或参加完整测试，获得即时反馈和详细解释。',
    'Start Custom Practice': '开始自定义练习',
    'Take Full Practice Test': '参加完整练习测试',
    'Why Choose Our SSAT Practice Platform?': '为什么选择我们的SSAT练习平台？',
    'Our AI-powered platform provides the most comprehensive and authentic SSAT preparation experience available.': '我们的AI平台提供最全面和真实的SSAT备考体验。',
    'AI-Generated Questions': 'AI生成题目',
    'Get unlimited, unique practice questions that match the exact format and difficulty of the real SSAT exam.': '获得无限的独特练习题，完全匹配真实SSAT考试的格式和难度。',
    'Targeted Practice': '针对性练习',
    'Focus on specific topics within Math, Verbal, Reading, and Writing sections to strengthen weak areas.': '专注于数学、语言、阅读和写作部分的特定主题，加强薄弱环节。',
    'Instant Feedback': '即时反馈',
    'Get detailed explanations for every question to understand concepts and improve your performance.': '每道题都有详细解释，帮助理解概念并提高成绩。',
    'Choose Your Practice Mode': '选择练习模式',
    'Flexible options to match your study schedule and goals.': '灵活的选项匹配您的学习计划和目标。',
    'Custom Section Practice': '自定义部分练习',
    'Targeted Learning': '针对性学习',
    'Choose any section (Math, Verbal, Reading, Writing)': '选择任何部分（数学、语言、阅读、写作）',
    'Select difficulty level and number of questions': '选择难度级别和题目数量',
    'Focus on specific topics within sections': '专注于部分内的特定主题',
    'Perfect for quick practice sessions': '适合快速练习',
    'Full Practice Test': '完整练习测试',
    'Complete Assessment': '完整评估',
    'Standard SSAT format with multiple sections': '标准SSAT格式，包含多个部分',
    'Customizable section configuration': '可自定义部分配置',
    'Comprehensive answer key with explanations': '带解释的综合答案',
    'PDF export for offline practice': 'PDF导出供离线练习',
    'SSAT Test Sections': 'SSAT测试部分',
    'Comprehensive coverage of all SSAT sections with authentic question types.': '全面覆盖所有SSAT部分，包含真实题型。',
    'Math': '数学',
    'Arithmetic, algebra, geometry, and data analysis': '算术、代数、几何和数据分析',
    'Verbal': '语言',
    'Synonyms, analogies, and vocabulary': '同义词、类比和词汇',
    'Reading': '阅读',
    'Reading comprehension passages and questions': '阅读理解文章和问题',
    'Writing': '写作',
    'Grammar, usage, and writing mechanics': '语法、用法和写作技巧'
  }

  const t = (key: string) => showChinese ? (translations[key as keyof typeof translations] || key) : key

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      {/* Hero Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              {t('Master the')} <span className="text-blue-600">{t('SSAT')}</span> {t('with')}
              <br />
              <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                {t('AI-Generated Practice')}
              </span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
              {t('Get unlimited, personalized SSAT practice questions generated by advanced AI. Practice individual sections or take full-length tests with instant feedback and detailed explanations.')}
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/custom-section">
                <Button size="lg" className="inline-flex items-center px-8 py-4 text-lg shadow-lg hover:shadow-xl">
                  <Target className="mr-2 h-5 w-5" />
                  {t('Start Custom Practice')}
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
              <Link href="/full-test">
                <Button 
                  variant="outline" 
                  size="lg" 
                  className="inline-flex items-center px-8 py-4 text-lg bg-white/80 backdrop-blur-sm border-2 border-blue-600 text-blue-600 hover:bg-blue-50"
                >
                  <BookOpen className="mr-2 h-5 w-5" />
                  {t('Take Full Practice Test')}
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              {t('Why Choose Our SSAT Practice Platform?')}
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              {t('Our AI-powered platform provides the most comprehensive and authentic SSAT preparation experience available.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center p-8 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100">
              <div className="bg-blue-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6">
                <Zap className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('AI-Generated Questions')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Get unlimited, unique practice questions that match the exact format and difficulty of the real SSAT exam.')}
              </p>
            </div>
            
            <div className="text-center p-8 rounded-2xl bg-gradient-to-br from-green-50 to-emerald-50 border border-green-100">
              <div className="bg-green-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6">
                <Target className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('Targeted Practice')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Focus on specific topics within Math, Verbal, Reading, and Writing sections to strengthen weak areas.')}
              </p>
            </div>
            
            <div className="text-center p-8 rounded-2xl bg-gradient-to-br from-purple-50 to-pink-50 border border-purple-100">
              <div className="bg-purple-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6">
                <Award className="h-8 w-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">{t('Instant Feedback')}</h3>
              <p className="text-gray-600 leading-relaxed">
                {t('Get detailed explanations for every question to understand concepts and improve your performance.')}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Test Modes Section */}
      <section className="py-20 bg-gray-50/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('Choose Your Practice Mode')}</h2>
            <p className="text-lg text-gray-600">
              {t('Flexible options to match your study schedule and goals.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            <Link href="/custom-section" className="group">
              <div className="bg-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-200 border border-gray-200 group-hover:border-blue-300 group-hover:scale-105">
                <div className="flex items-center mb-6">
                  <div className="bg-blue-100 p-3 rounded-xl mr-4">
                    <FileText className="h-8 w-8 text-blue-600" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-semibold text-gray-900">{t('Custom Section Practice')}</h3>
                    <p className="text-blue-600 font-medium">{t('Targeted Learning')}</p>
                  </div>
                </div>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Choose any section (Math, Verbal, Reading, Writing)')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Select difficulty level and number of questions')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Focus on specific topics within sections')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Perfect for quick practice sessions')}</span>
                  </li>
                </ul>
              </div>
            </Link>
            
            <Link href="/full-test" className="group">
              <div className="bg-white p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-200 border border-gray-200 group-hover:border-blue-300 group-hover:scale-105">
                <div className="flex items-center mb-6">
                  <div className="bg-indigo-100 p-3 rounded-xl mr-4">
                    <BookOpen className="h-8 w-8 text-indigo-600" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-semibold text-gray-900">{t('Full Practice Test')}</h3>
                    <p className="text-indigo-600 font-medium">{t('Complete Assessment')}</p>
                  </div>
                </div>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Standard SSAT format with multiple sections')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Customizable section configuration')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('Comprehensive answer key with explanations')}</span>
                  </li>
                  <li className="flex items-center">
                    <Clock className="h-4 w-4 text-green-500 mr-3" />
                    <span>{t('PDF export for offline practice')}</span>
                  </li>
                </ul>
              </div>
            </Link>
          </div>
        </div>
      </section>

      {/* SSAT Sections Info */}
      <section className="py-20 bg-white/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('SSAT Test Sections')}</h2>
            <p className="text-lg text-gray-600">
              {t('Comprehensive coverage of all SSAT sections with authentic question types.')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                title: t('Math'),
                description: t('Arithmetic, algebra, geometry, and data analysis'),
                topics: ['Fractions', 'Algebra', 'Geometry', 'Word Problems'],
                color: 'blue',
                bgColor: 'bg-blue-100',
                textColor: 'text-blue-600'
              },
              {
                title: t('Verbal'),
                description: t('Synonyms, analogies, and vocabulary'),
                topics: ['Synonyms', 'Analogies', 'Vocabulary', 'Word Relationships'],
                color: 'green',
                bgColor: 'bg-green-100',
                textColor: 'text-green-600'
              },
              {
                title: t('Reading'),
                description: t('Reading comprehension passages and questions'),
                topics: ['Literature', 'Science', 'History', 'Critical Reading'],
                color: 'purple',
                bgColor: 'bg-purple-100',
                textColor: 'text-purple-600'
              },
              {
                title: t('Writing'),
                description: t('Grammar, usage, and writing mechanics'),
                topics: ['Grammar', 'Punctuation', 'Sentence Structure', 'Style'],
                color: 'orange',
                bgColor: 'bg-orange-100',
                textColor: 'text-orange-600'
              }
            ].map((section, index) => (
              <div key={index} className="bg-white rounded-xl p-6 border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                <div className={`w-12 h-12 ${section.bgColor} rounded-lg flex items-center justify-center mb-4`}>
                  <span className={`${section.textColor} font-bold text-lg`}>
                    {section.title[0]}
                  </span>
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{section.title}</h3>
                <p className="text-gray-600 text-sm mb-4">{section.description}</p>
                <div className="space-y-1">
                  {section.topics.map((topic, topicIndex) => (
                    <span key={topicIndex} className="inline-block bg-gray-100 px-2 py-1 rounded text-xs text-gray-600 mr-1 mb-1">
                      {topic}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}